### ISSUE TITLE
Small bugfix

### ISSUE THREAD

**Issue by sxiii** [ingar195/price-tracker#18]
Greetings.

The parser wasn't working for me - and this fixed the issue:
* https://github.com/GustavoKatel/pushbullet-cli/commit/27ee63bf8162b0a458fbda4b2f554446406465f1

So basically in the `tracker.py` file we need to change line `apiKey = f.readline()` to `apiKey = f.readline().rstrip()`. After that it works perfectly :)

**Comment by ingar195** [comment]
Hi sorry for the long response time. did not have notifications on for github.

Have added you fix
