### ISSUE TITLE
Add support for prisjakt

### ISSUE THREAD

**Issue by sxiii** [ingar195/price-tracker#19]
Would be really nice to have prisjakt included as well. Let me know if you need help in implementing the support. Thanks!

**Comment by ingar195** [comment]
Hi, totally agree that prisjakt.no should be added. 
Feel free to create a branch and a pull request.

I have notifications on now, so will follow up faster from now on

**Comment by ingar195** [comment]
I have added support for prisjakt now

**Comment by ingar195** [comment]
I have added support for prisjakt now
